project:
  type: website 
  output-dir: docs
  render:
    - sessions/*.md
    - sessions/*.qmd
    - sessions/*.ipynb

website:
  title: "A Living Book for Notes on Graph Neural Networks"


format:
  html:
    theme: simplex

execute:
  freeze: auto

