project:
  type: book
  output-dir: docs 

book:
  title: "A Living Book for Notes on Graph Neural Networks"
  author: "The Alan Turing Institute"
  date: "25/06/2024"
  chapters:
    - index.qmd
    - graphs-and-sets.md
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: simplex
  pdf:
    documentclass: scrreprt

execute:
  freeze: auto

